### ISSUE TITLE
blookmarklet broken

### ISSUE THREAD

**Issue by randomblookethakker** [Minesraft2/Blooket-Cheats#619]
### Script

Unknown

### Problem

The unobfuscusated blookmarkets are broken and will not show GUI, mobile GUI, or anything in any of the gamemode hacks.

### Method

Imported Bookmarklets.html

### Type

Unobfuscated

### Extra Info

has been happening minimum 14 hours

**Comment by Minesraft2** [comment]
When's the last time you updated your scripts

**Comment by bloohacked** [comment]
fixed in the newest update

**Comment by randomblookethakker** [comment]
says fixed but it still is like this. i re-imported it but it still isn't working

**Comment by Minesraft2** [comment]
Console errors?

**Comment by Minesraft2** [comment]
Stale
